# Generated by Django 4.2 on 2023-08-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PDMApp", "0002_sharedocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedocument",
            name="owner",
        ),
    ]
